apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-node
spec:
  replicas: {{ default 2 .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: {{ .Release.Name }}-server
          image: prowave/{{ .Chart.Name }}:{{ .Chart.AppVersion }}
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: JAVA_OPTS
              value: "-Dexternal.server.url={{ .Values.external.server.url }} -Denv={{ .Values.env }} -Xms1g -Xmx1g -Xrs -XX:+UseG1GC -XX:NewRatio=3"
          ports:
            - containerPort: 8080
              name: tc-port
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: {{ .Values.nodeSelector.role }}